import Foundation

/// Represents a HitObject with additional information for osu!droid difficulty calculation.
public class DroidDifficultyHitObject: DifficultyHitObject {
    public override var mode: GameMode {
        return .droid
    }

    public override var maximumSliderRadius: Float {
        return DifficultyHitObject.normalizedRadius * 2.0
    }

    public override var smallCircleBonus: Double {
        return max(1.0, 1.0 + pow(Double(70.0 - obj.difficultyRadius) / 50.0, 2.0))
    }

    /// The rhythm multiplier generated by the HitObject.
    public var rhythmMultiplier: Double = 1.0

    /// Adjusted preempt time of the HitObject, taking speed multiplier into account.
    public let timePreempt: Double

    init(
        obj: HitObject,
        lastObj: HitObject?,
        clockRate: Double,
        difficultyHitObjects: [DroidDifficultyHitObject],
        index: Int
    ) {
        self.timePreempt = obj.timePreempt / clockRate
        super.init(
            obj: obj,
            lastObj: lastObj,
            clockRate: clockRate,
            difficultyHitObjects: difficultyHitObjects,
            index: index
        )
    }

    public override func previous(_ backwardsIndex: Int) -> DifficultyHitObject? {
        let prevIndex = index - backwardsIndex
        if prevIndex >= 0 {
            return difficultyHitObjects[prevIndex]
        }
        return nil
    }

    public override func next(_ forwardsIndex: Int) -> DifficultyHitObject? {
        let nextIndex = index + forwardsIndex + 2
        if nextIndex < difficultyHitObjects.count {
            return difficultyHitObjects[nextIndex]
        }
        return nil
    }

    public override func opacityAt(time: Double, mods: [Mod]) -> Double {
        if obj is HitCircle && mods.contains(where: { $0 is ModTraceable }) {
            return 0.0
        }
        return super.opacityAt(time: time, mods: mods)
    }

    /// Determines whether this DroidDifficultyHitObject is considered overlapping with the DroidDifficultyHitObject before it.
    public func isOverlapping(considerDistance: Bool) -> Bool {
        if obj is Spinner {
            return false
        }

        guard let previous = previous(0) as? DroidDifficultyHitObject, !(previous.obj is Spinner) else {
            return false
        }

        if deltaTime >= 5.0 {
            return false
        }

        if considerDistance {
            let position = obj.difficultyStackedPosition
            var distanceSquared = previous.obj.difficultyStackedEndPosition.getDistanceSquared(position)

            if let lazyEnd = previous.lazyEndPosition {
                distanceSquared = min(distanceSquared, lazyEnd.getDistanceSquared(position))
            }

            let threshold = 2.0 * obj.difficultyRadius
            let thresholdSquared = threshold * threshold

            return distanceSquared <= thresholdSquared
        }

        return true
    }
}
