import Foundation

/// Represents a slider.
class Slider: HitObject {

    // MARK: - Constants

    static let legacyLastTickOffset: Double = 36.0

    /// Scoring distance with a speed-adjusted beat length of 1 second
    /// (i.e. the speed slider balls move through their track).
    static let baseScoringDistance: Float = 100

    private static let baseNormalSlideSample = BankHitSampleInfo(name: "sliderslide")
    private static let baseWhistleSlideSample = BankHitSampleInfo(name: "sliderwhistle")
    private static let baseTickSample = BankHitSampleInfo(name: "slidertick")

    // MARK: - Stored Properties

    override var endTime: Double {
        startTime + Double(spanCount) * path.expectedDistance / velocity
    }

    /// The path of this `Slider`.
    var path: SliderPath {
        didSet {
            updateNestedPositions()
        }
    }

    override var position: Vector2 {
        didSet {
            updateNestedPositions()
        }
    }

    private let endPositionCache: Cached<Vector2>

    override var endPosition: Vector2 {
        if !endPositionCache.isValid {
            endPositionCache.value = position + curvePositionAt(1.0)
        }
        return endPositionCache.value
    }

    /// The distance of this `Slider`.
    var distance: Double {
        path.expectedDistance
    }

    /// The amount of times this `Slider` repeats.
    var repeatCount: Int {
        didSet {
            repeatCount = max(repeatCount, 0)
            updateNestedPositions()
        }
    }

    /// The amount of times the length of this `Slider` spans.
    var spanCount: Int {
        repeatCount + 1
    }

    /// The nested hit objects of this `Slider`.
    ///
    /// Consists of a `SliderHead`, `SliderTick`s, `SliderRepeat`s, and a `SliderTail`.
    private(set) var nestedHitObjects = [SliderHitObject]()

    /// The computed velocity of this `Slider`. This is the amount of path distance travelled in 1 ms.
    private(set) var velocity: Double = 0

    /// Spacing between `SliderTick`s of this `Slider`.
    private(set) var tickDistance: Double = 0

    /// An extra multiplier that affects the number of `SliderTick`s generated by this `Slider`.
    /// An increase in this value increases `tickDistance`, which reduces the number of ticks generated.
    var tickDistanceMultiplier: Double = 1.0

    /// Whether `SliderTick`s should be generated by this object.
    ///
    /// This exists for backwards compatibility with maps that abuse NaN slider velocity behavior
    /// on osu!stable (e.g. /b/2628991).
    var generateTicks: Bool = true

    /// The head of the `Slider`.
    private(set) var head: SliderHead!

    /// The tail of the `Slider`.
    private(set) var tail: SliderTail!

    /// The duration of one span of this `Slider` in milliseconds.
    var spanDuration: Double {
        duration / Double(spanCount)
    }

    /// The samples to be played when each node of this `Slider` is hit.
    ///
    /// - 0: The first node.
    /// - 1: The first repeat.
    /// - 2: The second repeat.
    /// - ...
    /// - `n - 1`: The last repeat.
    /// - `n`: The last node.
    var nodeSamples: [[HitSampleInfo]]

    override var stackOffsetMultiplier: Float {
        didSet {
            guard oldValue != stackOffsetMultiplier else { return }
            difficultyStackedEndPositionCache.invalidate()
            gameplayStackedEndPositionCache.invalidate()
            nestedHitObjects.forEach { $0.stackOffsetMultiplier = stackOffsetMultiplier }
        }
    }

    // MARK: - Difficulty Calculation Object Positions

    private let difficultyStackedEndPositionCache: Cached<Vector2>

    override var difficultyStackedEndPosition: Vector2 {
        if !difficultyStackedEndPositionCache.isValid {
            difficultyStackedEndPositionCache.value = endPosition + difficultyStackOffset
        }
        return difficultyStackedEndPositionCache.value
    }

    override var difficultyStackHeight: Int {
        didSet {
            guard oldValue != difficultyStackHeight else { return }
            difficultyStackedEndPositionCache.invalidate()
            nestedHitObjects.forEach { $0.difficultyStackHeight = difficultyStackHeight }
        }
    }

    override var difficultyScale: Float {
        didSet {
            guard oldValue != difficultyScale else { return }
            difficultyStackedEndPositionCache.invalidate()
            nestedHitObjects.forEach { $0.difficultyScale = difficultyScale }
        }
    }

    // MARK: - Gameplay Object Positions

    private let gameplayStackedEndPositionCache: Cached<Vector2>

    override var gameplayStackedEndPosition: Vector2 {
        if !gameplayStackedEndPositionCache.isValid {
            gameplayStackedEndPositionCache.value = endPosition + gameplayStackOffset
        }
        return gameplayStackedEndPositionCache.value
    }

    private let screenSpaceGameplayStackedEndPositionCache: Cached<Vector2>

    override var screenSpaceGameplayStackedEndPosition: Vector2 {
        if !screenSpaceGameplayStackedEndPositionCache.isValid {
            screenSpaceGameplayStackedEndPositionCache.value =
                convertPositionToRealCoordinates(gameplayStackedEndPosition)
        }
        return screenSpaceGameplayStackedEndPositionCache.value
    }

    override var gameplayStackHeight: Int {
        didSet {
            guard oldValue != gameplayStackHeight else { return }
            gameplayStackedEndPositionCache.invalidate()
            screenSpaceGameplayStackedEndPositionCache.invalidate()
            nestedHitObjects.forEach { $0.gameplayStackHeight = gameplayStackHeight }
        }
    }

    override var gameplayScale: Float {
        didSet {
            guard oldValue != gameplayScale else { return }
            gameplayStackedEndPositionCache.invalidate()
            screenSpaceGameplayStackedEndPositionCache.invalidate()
            nestedHitObjects.forEach { $0.gameplayScale = gameplayScale }
        }
    }

    // MARK: - Initialization

    /// Creates a new `Slider`.
    ///
    /// - Parameters:
    ///   - startTime: The time at which this `Slider` starts, in milliseconds.
    ///   - position: The position of the `Slider` relative to the play field.
    ///   - repeatCount: The repetition amount of this `Slider`. Note that 1 repetition means no repeats (1 loop).
    ///   - path: The path of this `Slider`.
    ///   - isNewCombo: Whether this `Slider` starts a new combo.
    ///   - comboOffset: When starting a new combo, the offset of the new combo relative to the current one.
    ///   - nodeSamples: The samples to be played when each node of this `Slider` is hit.
    init(
        startTime: Double,
        position: Vector2,
        repeatCount: Int,
        path: SliderPath,
        isNewCombo: Bool,
        comboOffset: Int,
        nodeSamples: [[HitSampleInfo]]
    ) {
        self.repeatCount = repeatCount
        self.path = path
        self.nodeSamples = nodeSamples

        // Initialize caches before super.init
        self.endPositionCache = Cached(position)
        self.difficultyStackedEndPositionCache = Cached(position)
        self.gameplayStackedEndPositionCache = Cached(position)
        self.screenSpaceGameplayStackedEndPositionCache = Cached(Vector2.zero)

        super.init(startTime: startTime, position: position, isNewCombo: isNewCombo, comboOffset: comboOffset)
    }

    // MARK: - Methods

    override func applyDefaults(controlPoints: BeatmapControlPoints, difficulty: BeatmapDifficulty, mode: GameMode) {
        super.applyDefaults(controlPoints: controlPoints, difficulty: difficulty, mode: mode)

        let timingPoint = controlPoints.timing.controlPointAt(startTime)
        let difficultyPoint = controlPoints.difficulty.controlPointAt(startTime)

        let sliderVelocityAsBeatLength = -100.0 / difficultyPoint.speedMultiplier
        let bpmMultiplier: Double =
            if sliderVelocityAsBeatLength < 0 {
                Double(Float(-sliderVelocityAsBeatLength).clamped(to: 10...1000)) / 100.0
            } else {
                1.0
            }

        velocity = Double(Slider.baseScoringDistance) * difficulty.sliderMultiplier / (timingPoint.msPerBeat * bpmMultiplier)

        // WARNING: this is intentionally not computed as `BASE_SCORING_DISTANCE * difficulty.sliderMultiplier`
        // for backwards compatibility reasons (intentionally introducing floating point errors to match osu!stable).
        let scoringDistance = velocity * timingPoint.msPerBeat

        generateTicks = difficultyPoint.generateTicks

        tickDistance =
            generateTicks
            ? scoringDistance / difficulty.sliderTickRate * tickDistanceMultiplier
            : Double.infinity

        // Invalidate the end position in case there are timing changes.
        invalidateEndPositions()

        createNestedHitObjects(controlPoints: controlPoints)

        nestedHitObjects.forEach {
            $0.applyDefaults(controlPoints: controlPoints, difficulty: difficulty, mode: mode)
        }
    }

    override func applySamples(controlPoints: BeatmapControlPoints) {
        let sampleControlPoint = controlPoints.sample.controlPointAt(
            startTime + Double(HitObject.controlPointLeniency) + 1
        )

        samples = samples.map { sampleControlPoint.applyTo(hitSampleInfo: applyTo($0)) }

        for i in nodeSamples.indices {
            let time = startTime + Double(i) * spanDuration + Double(HitObject.controlPointLeniency)
            let nodeSamplePoint = controlPoints.sample.controlPointAt(time)

            nodeSamples[i] = nodeSamples[i].map { nodeSamplePoint.applyTo(hitSampleInfo: applyTo($0)) }
        }

        createSlidingSamples(controlPoints: controlPoints)
        updateNestedSamples(controlPoints: controlPoints)
    }

    /// Computes the position on this `Slider` relative to how much of this `Slider` has been completed in osu!pixels.
    ///
    /// - Parameter progress: `[0, 1]` where 0 is the start time and 1 is the end time of this `Slider`.
    /// - Returns: The position on the `Slider`.
    func curvePositionAt(_ progress: Double) -> Vector2 {
        path.positionAt(progressAt(progress))
    }

    /// Computes the progress along this `Slider` relative to how much of this `Slider` has been completed.
    ///
    /// - Parameter progress: `[0, 1]` where 0 is the start time and 1 is the end time of this `Slider`.
    /// - Returns: `[0, 1]` where 0 is the beginning and 1 is the end of this `Slider`.
    func progressAt(_ progress: Double) -> Double {
        var p = progress * Double(spanCount).truncatingRemainder(dividingBy: 1)
        // Manually compute: progress * spanCount mod 1
        let full = progress * Double(spanCount)
        p = full - floor(full)

        if spanAt(progress) % 2 == 1 {
            p = 1 - p
        }

        return p
    }

    /// Determines which span of this `Slider` the progress point is on.
    ///
    /// - Parameter progress: `[0, 1]` where 0 is the start time and 1 is the end time of this `Slider`.
    /// - Returns: `[0, spanCount)` where 0 is the first run.
    func spanAt(_ progress: Double) -> Int {
        Int(progress * Double(spanCount))
    }

    override func createHitWindow(mode: GameMode) -> HitWindow? {
        EmptyHitWindow()
    }

    // MARK: - Private Methods

    private func createNestedHitObjects(controlPoints: BeatmapControlPoints) {
        // A very lenient maximum length of a slider for ticks to be generated.
        // This exists for edge cases such as /b/1573664 where the beatmap has been edited by the user,
        // and should never be reached in normal usage.
        let maxLength: Double = 100000.0
        let length = min(maxLength, path.expectedDistance)
        let clampedTickDistance = tickDistance.clamped(to: 0.0...length)
        let minDistanceFromEnd = velocity * 10

        let tickDistanceLimit = length - minDistanceFromEnd
        let ticksPerSpan: Int =
            if clampedTickDistance == 0 || tickDistanceLimit <= 0 {
                0
            } else {
                max(Int(ceil(tickDistanceLimit / clampedTickDistance)) - 1, 0)
            }

        // Total nested objects: head + tail + repeats + all ticks across spans.
        nestedHitObjects = []
        nestedHitObjects.reserveCapacity(2 + (spanCount - 1) + ticksPerSpan * spanCount)

        head = SliderHead(startTime: startTime, position: position)
        nestedHitObjects.append(head)

        for span in 0..<spanCount {
            if clampedTickDistance != 0 {
                let spanStartTime = startTime + Double(span) * spanDuration
                let reversed = span % 2 == 1
                var sliderTicks = [SliderTick]()
                sliderTicks.reserveCapacity(ticksPerSpan)

                var d = clampedTickDistance
                while d <= length {
                    if d >= tickDistanceLimit {
                        break
                    }

                    // Always generate ticks from the start of the path rather than the span to ensure
                    // that ticks in repeat spans are positioned identically to those in non-repeat spans
                    let distanceProgress = d / length
                    let timeProgress = reversed ? 1 - distanceProgress : distanceProgress
                    let pathPosition = path.positionAt(distanceProgress)
                    let tickPosition = Vector2(
                        x: position.x + pathPosition.x,
                        y: position.y + pathPosition.y
                    )

                    sliderTicks.append(
                        SliderTick(
                            startTime: spanStartTime + timeProgress * spanDuration,
                            position: tickPosition,
                            spanIndex: span,
                            spanStartTime: spanStartTime
                        )
                    )

                    d += clampedTickDistance
                }

                // For repeat spans, ticks are returned in reverse-StartTime order.
                if reversed {
                    sliderTicks.reverse()
                }

                nestedHitObjects.append(contentsOf: sliderTicks)
            }

            if span < spanCount - 1 {
                nestedHitObjects.append(SliderRepeat(slider: self, spanIndex: span))
            }
        }

        tail = SliderTail(slider: self)
        nestedHitObjects.append(tail)

        nestedHitObjects.sort { $0.startTime < $1.startTime }

        updateNestedSamples(controlPoints: controlPoints)
    }

    private func updateNestedPositions() {
        invalidateEndPositions()

        guard head != nil, tail != nil else { return }

        head.position = position
        tail.position = endPosition

        for i in 1..<(nestedHitObjects.count - 1) {
            let nestedHitObject = nestedHitObjects[i]
            let progress = (nestedHitObject.startTime - startTime) / duration
            let curvePosition = curvePositionAt(progress)

            nestedHitObject.position = Vector2(
                x: position.x + curvePosition.x,
                y: position.y + curvePosition.y
            )
        }
    }

    private func invalidateEndPositions() {
        endPositionCache.invalidate()
        difficultyStackedEndPositionCache.invalidate()
        gameplayStackedEndPositionCache.invalidate()
        screenSpaceGameplayStackedEndPositionCache.invalidate()
    }

    private func createSlidingSamples(controlPoints: BeatmapControlPoints) {
        auxiliarySamples.removeAll()

        let bankSamples = samples.compactMap { $0 as? BankHitSampleInfo }
        let normalSlide = bankSamples.first { $0.name == BankHitSampleInfo.hitNormal }
        let whistleSlide = bankSamples.first { $0.name == BankHitSampleInfo.hitWhistle }

        if normalSlide == nil && whistleSlide == nil {
            return
        }

        let samplePoints = controlPoints.sample.between(
            startTime + Double(HitObject.controlPointLeniency),
            endTime + Double(HitObject.controlPointLeniency)
        )

        if normalSlide != nil {
            auxiliarySamples.append(SequenceHitSampleInfo(
                samples: samplePoints.map { point in
                    (point.time, point.applyTo(Slider.baseNormalSlideSample))
                }
            ))
        }

        if whistleSlide != nil {
            auxiliarySamples.append(SequenceHitSampleInfo(
                samples: samplePoints.map { point in
                    (point.time, point.applyTo(Slider.baseWhistleSlideSample))
                }
            ))
        }
    }

    private func updateNestedSamples(controlPoints: BeatmapControlPoints) {
        // Ensure that the list of node samples is at least as long as the number of nodes
        while nodeSamples.count < repeatCount + 2 {
            nodeSamples.append(samples.map { $0.copy() })
        }

        for nested in nestedHitObjects {
            nested.samples.removeAll()

            if let head = nested as? SliderHead {
                head.samples.append(contentsOf: nodeSamples[0])
            } else if let rep = nested as? SliderRepeat {
                rep.samples.append(contentsOf: nodeSamples[rep.spanIndex + 1])
            } else if nested is SliderTail {
                nested.samples.append(contentsOf: nodeSamples[spanCount])
            } else {
                let time = nested.startTime + Double(HitObject.controlPointLeniency)
                let tickSamplePoint = controlPoints.sample.controlPointAt(time)
                nested.samples.append(tickSamplePoint.applyTo(hitSampleInfo: Slider.baseTickSample))
            }
        }
    }
}

// MARK: - Private Extensions

private extension Double {
    func clamped(to range: ClosedRange<Double>) -> Double {
        Swift.min(Swift.max(self, range.lowerBound), range.upperBound)
    }
}

private extension Float {
    func clamped(to range: ClosedRange<Float>) -> Float {
        Swift.min(Swift.max(self, range.lowerBound), range.upperBound)
    }
}
